ALTER TABLE TAGS ADD COLUMN DELETE INTEGER NOT NULL DEFAULT 0;
ALTER TABLE TAGS ADD COLUMN VERSION INTEGER NOT NULL DEFAULT 1;

ALTER TABLE TAG_JOT ADD COLUMN DELETE INTEGER NOT NULL DEFAULT 0;
ALTER TABLE TAG_JOT ADD COLUMN VERSION INTEGER NOT NULL DEFAULT 1;

ALTER TABLE ATTACHMENTS ADD COLUMN DELETE INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ATTACHMENTS ADD COLUMN VERSION INTEGER NOT NULL DEFAULT 1;

ALTER TABLE JOTS ADD COLUMN DELETE INTEGER NOT NULL DEFAULT 0;
ALTER TABLE JOTS ADD COLUMN VERSION INTEGER NOT NULL DEFAULT 1;