exclude_patterns:
  - .idea
  - app/src/main/res
engines:
  duplication:
    enabled: false
  checkstyle:
    enabled: true
    checks:
      com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:
        enabled: false